version: '3.8'

networks:
  app-network:

volumes:
  app-data:
  postgres:
  pgadmin:

services:
  postgres:
    build:
      context: .docker/pgsql
      dockerfile: Dockerfile
    container_name: postgresfb
    shm_size: 1g
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      app-network:
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadminfb
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      app-network:
    restart: unless-stopped

  web:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: webfb
    depends_on:
      - postgres
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserverfb
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  node:
    container_name: nodefb
    build:
      context: .docker/node
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    networks:
      app-network: